### ISSUE TITLE
False positive bitcanna.io

### ISSUE THREAD

**Issue by BitCannaGlobal** [AmmoniteFilter/TrilobiteFilter#1]
BitCanna is now marked in your list. BitCanna is not a company involved in spam, but focusses on solving issues in the cannabis industries using blockchain technology. Please remove our domain from your list (https://raw.githubusercontent.com/AmmoniteFilter/TrilobiteFilter/main/filter.txt). Thanks!

**Comment by ammnt** [comment]
> BitCanna is now marked in your list. BitCanna is not a company involved in spam, but focusses on solving issues in the cannabis industries using blockchain technology. Please remove our domain from your list (https://raw.githubusercontent.com/AmmoniteFilter/TrilobiteFilter/main/filter.txt). Thanks!

Hello! Removed and will be available in the next release in Friday. Thank you😙

**Comment by BitCannaGlobal** [comment]
Good day

Thanks!

With kind regards
The BitCanna team
